# Generated by Django 6.0.5 on 2026-05-28 18:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la boutique')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug URL')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('langue_defaut', models.CharField(choices=[('fr', 'Français'), ('ar', 'Arabe'), ('ar_fr', 'Arabe + Français')], default='ar_fr', max_length=5, verbose_name='Langue par défaut')),
                ('whatsapp_numero', models.CharField(blank=True, max_length=20, verbose_name='Numéro WhatsApp principal')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Boutique',
                'verbose_name_plural': 'Boutiques',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_numero', models.CharField(max_length=20, verbose_name='Numéro WhatsApp')),
                ('nom_complet', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.boutique', verbose_name='Boutique')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom_complet'],
                'unique_together': {('boutique', 'whatsapp_numero')},
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(max_length=30, verbose_name='Numéro de commande')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('sans_reponse', 'Sans réponse'), ('injoignable', 'Injoignable'), ('expediee', 'Expédiée'), ('livree', 'Livrée'), ('refusee_livraison', 'Refusée à la livraison')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais de livraison (MAD)')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total (MAD)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='core.boutique', verbose_name='Boutique')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='core.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_creation'],
                'unique_together': {('boutique', 'numero_commande')},
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=300, verbose_name='Nom du produit')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (MAD)')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core.commande', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du template')),
                ('type', models.CharField(choices=[('confirmation', 'Confirmation de commande'), ('relance', 'Relance sans réponse'), ('expedition', "Avis d'expédition"), ('autre', 'Autre')], max_length=20, verbose_name='Type de message')),
                ('contenu_fr', models.TextField(help_text='Variables : {nom_client}  {numero_commande}  {montant}', verbose_name='Contenu en français')),
                ('contenu_ar', models.TextField(help_text='المتغيرات : {nom_client}  {numero_commande}  {montant}', verbose_name='Contenu en arabe')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='core.boutique', verbose_name='Boutique')),
            ],
            options={
                'verbose_name': 'Template de message',
                'verbose_name_plural': 'Templates de messages',
                'ordering': ['boutique', 'type', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu_envoye', models.TextField(verbose_name='Contenu envoyé')),
                ('statut_envoi', models.CharField(choices=[('en_attente', "En attente d'envoi"), ('envoye', 'Envoyé'), ('echec', "Échec d'envoi"), ('livre', 'Livré (WhatsApp confirmé)'), ('lu', 'Lu par le destinataire')], default='en_attente', max_length=15, verbose_name="Statut d'envoi")),
                ('reponse_recue', models.TextField(blank=True, verbose_name='Réponse du client')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='Date de la réponse')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.commande', verbose_name='Commande')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_envoyes', to='core.template', verbose_name='Template utilisé')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('proprietaire', 'Propriétaire'), ('employe', 'Employé')], default='employe', max_length=20, verbose_name='Rôle')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.boutique', verbose_name='Boutique')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Membership',
                'verbose_name_plural': 'Memberships',
                'ordering': ['boutique', 'role'],
                'unique_together': {('user', 'boutique')},
            },
        ),
    ]
